### ISSUE TITLE
Expose range as a first class concept

### ISSUE THREAD

**Issue by stew** [stew/dogs#15]
Diet has a Range type that it uses intenerally. We could move this out from inside Diet and expose it as a first class data type as a replacement for Range from the scala standard library

**Comment by anicolaspp** [comment]
The scala Range is only for Int. Do you want to have the Range I implemented for Diet in the same way it is now (generic that uses a generator function)? or like the one in scala standard library?

**Comment by anicolaspp** [comment]
can we have a common interface that describe functions like foldRight, foldLeft, map, ... so we can use it as a base concept for the other structures?

**Comment by tpolecat** [comment]
We use typeclasses to abstract over operations like `fold` and `map` (in this case `Foldable` and `Functor`) … in general you can't express this kind of thing with subclassing (stdlib tries and it's a disaster).

**Comment by anicolaspp** [comment]
do we have type class for this already?

**Comment by anicolaspp** [comment]
how exactly it's done?
