### ISSUE TITLE
improve how we add ranges to Diet

### ISSUE THREAD

**Issue by stew** [stew/dogs#17]
right now in Diet, if you add a range of values, it adds them one by one. So adding a range is O(n) on the size of the range, but we should be able to make this O(log n) on the size of the tree.

If you think about it, adding 0 - 100000 to an empty diet should just be a single operation, right now it is  100001 separate operations

**Comment by anicolaspp** [comment]
I will be taken care of this within this week.

**Comment by anicolaspp** [comment]
I am working on this now

**Comment by anicolaspp** [comment]
This is done already
