### ISSUE TITLE
Disjoint-set

### ISSUE THREAD

**Issue by lewismj** [stew/dogs#82]
Hi,
I have an initial (requires some tidy up, more tests, more detail on the documentation) implementation of a disjoint-set, here: https://github.com/lewismj/dogs/tree/feature/disjoint-set
Whilst it is a very simple data-structure, it is useful as a building-block to some graph structures/functions. And, I thought it would be a good starting point as I'd like to see if I could add to the dogs library.

I'd appreciate it if you could do a quick code review and let me know if (with a bit of cleanup) this is something that I could raise a PR for ?

Thanks,
Mike

**Comment by anicolaspp** [comment]
Would you create a PR?

**Comment by anicolaspp** [comment]
Actually, we could use this on Diet[A] when asking for all the ranges on the tree. The result right now is a disjoint set based on Range[A]

**Comment by lewismj** [comment]
Thanks, I will raise a PR ...  I will look to add some utility functions with the ability to union a set (it is a simple fold), as I think that would be used by graphs. Im not sure many people would use this data-structure directly - but it is useful implementing other stuff.

**Comment by anicolaspp** [comment]
i once talked to @stew about adding graph data structures / algorithms here but there is another lib from verizon (I think) already. Maybe it is something to consider again. At the NE Scala event this month, we should talk about the future of dog in general.

**Comment by lewismj** [comment]
I have some issues, the Travis CI, seemed to run again, but I'm getting decov issues:

decov/patch — No report found to compare against
codecov/project — No report found to compare against

I've not used decov/codecov, I will take a look, I guess there are some files I need to submit as part of the PR?

**Comment by lewismj** [comment]
hi, I'd appreciate it if someone (with permission) could try restarting the Travis build for my branch? Save me making minor w/s edits to trigger the build, hopefully Travis has sorted itself out...
